services:
  Buepro\UserPizpalue\Service\ExtensionInstallService:
    tags:
      - name: event.listener
        identifier: 'buepro/user-pizpalue/finalize-extension-installation'
        event: TYPO3\CMS\Extensionmanager\Event\AfterExtensionFilesHaveBeenImportedEvent
