rootPageId: 1
base: /
easyconf:
  data:
    admin:
      siteConfiguration:
        overwriteBase: '1'
        overwriteBaseVariants: '1'
        overwriteRobots: '1'
        overwriteSitemap: '1'
        manageNewsRouteEnhancer: '1'
        removeLegacyNewsRouteEnhancers: '1'
        overwritePageNotFound: '1'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: '0'
    base: /
    typo3Language: de
    locale: de_CH.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-CH
    direction: ltr
    flag: de
  -
    title: Français
    enabled: true
    languageId: '1'
    base: /fr/
    typo3Language: fr
    locale: fr_CH.UTF-8
    iso-639-1: fr
    navigationTitle: Français
    hreflang: fr-CH
    direction: ltr
    fallbackType: fallback
    fallbacks: '2,0'
    flag: fr
  -
    title: English
    enabled: true
    languageId: '2'
    base: /en/
    typo3Language: default
    locale: en_GB.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-GB
    direction: ltr
    fallbackType: fallback
    fallbacks: '0'
    flag: gb
